### ISSUE TITLE
Controllers are firing multiple times

### ISSUE THREAD

**Issue by shreysaroch** [cmacdonnacha/angularjs-foundation-boilerplate#4]
Just type console.log('something'); in your controller and see how many times it get printed in console.

**Comment by cmacdonnacha** [comment]
Thanks @shreycp , which controller?

**Comment by shreysaroch** [comment]
I've resolved the issue, as your ui-view is called twice because of layout.tpl.html. Try to route mobile view through some other file, by calculating screen size.
